version: '3'
services:
    web:
        image: nginx
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
    php:
        build: docker/php
        restart: always
        volumes:
            - ./docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - .:/var/www/html
    composer:
        image: composer
        volumes:
            - .:/app
        command: composer dump-autoload -o
